# Generated by Django 5.2.14 on 2026-05-28 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='依杋', max_length=80)),
                ('birth_date', models.DateField(default='2026-05-18')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('feeding', '餵食'), ('sleep', '睡眠'), ('diaper', '尿布'), ('health', '健康'), ('growth', '成長'), ('note', '備註')], max_length=20)),
                ('time', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('feed_kind', models.CharField(blank=True, max_length=40)),
                ('feed_amount', models.CharField(blank=True, max_length=80)),
                ('sleep_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('pee', models.BooleanField(default=False)),
                ('poop', models.BooleanField(default=False)),
                ('poop_amount', models.CharField(blank=True, max_length=40)),
                ('poop_color', models.CharField(blank=True, max_length=40)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('symptom', models.CharField(blank=True, max_length=120)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tracker.baby')),
            ],
            options={
                'ordering': ['-time', '-created_at'],
            },
        ),
    ]
